// Generated by CoffeeScript 2.7.0
(function() {
  /*
   * MusicPlayer — HTML5 Audio-based player with state machine, queue, crossfade,
   * repeat/shuffle, and localStorage-backed persistence.
   */
  var CONST, EventEmitter, MusicPlayer, REPEAT, STATES, VALID_TRANSITIONS, _clamp, _isArray, _isFunction, _isNumber, _isPlainObject, _isPositiveInt, _isString, _nowIso, _shuffleArr,
    boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } },
    indexOf = [].indexOf;

  CONST = require('./plan-enhancer-constants');

  ({_isNumber, _isPositiveInt, _isPlainObject} = CONST);

  // ── Frozen enums ──────────────────────────────────────────────────────
  STATES = Object.freeze({
    IDLE: 'idle',
    LOADING: 'loading',
    PLAYING: 'playing',
    PAUSED: 'paused',
    BUFFERING: 'buffering',
    ENDED: 'ended',
    ERROR: 'error'
  });

  REPEAT = Object.freeze({
    OFF: 'off',
    ONE: 'one',
    ALL: 'all'
  });

  // ── Valid state transitions (soft-validated — warns, doesn't block) ───
  VALID_TRANSITIONS = Object.freeze({
    idle: [STATES.LOADING, STATES.ERROR],
    loading: [STATES.PLAYING, STATES.PAUSED, STATES.BUFFERING, STATES.ERROR, STATES.IDLE],
    playing: [STATES.PAUSED, STATES.BUFFERING, STATES.ENDED, STATES.ERROR, STATES.IDLE, STATES.LOADING],
    paused: [STATES.PLAYING, STATES.LOADING, STATES.IDLE, STATES.ERROR],
    buffering: [STATES.PLAYING, STATES.PAUSED, STATES.ERROR, STATES.IDLE],
    ended: [STATES.PLAYING, STATES.LOADING, STATES.IDLE],
    error: [STATES.LOADING, STATES.IDLE, STATES.PLAYING, STATES.PAUSED]
  });

  // ── Helpers ───────────────────────────────────────────────────────────
  _isString = function(v) {
    return typeof v === 'string';
  };

  _isArray = function(v) {
    return Array.isArray(v);
  };

  _isFunction = function(v) {
    return typeof v === 'function';
  };

  _clamp = function(v, lo, hi) {
    v = Number(v);
    if (isNaN(v)) {
      return lo;
    }
    return Math.max(lo, Math.min(hi, v));
  };

  _nowIso = function() {
    try {
      return new Date().toISOString();
    } catch (error) {
      return '';
    }
  };

  _shuffleArr = function(arr) {
    var a, i, j;
    a = arr.slice();
    i = a.length - 1;
    while (i > 0) {
      j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
      i -= 1;
    }
    return a;
  };

  // ── EventEmitter ──────────────────────────────────────────────────────
  EventEmitter = class EventEmitter {
    constructor() {
      this._listeners = new Map();
    }

    on(evt, fn) {
      if (!_isFunction(fn)) {
        return;
      }
      evt = String(evt);
      if (!this._listeners.has(evt)) {
        this._listeners.set(evt, new Set());
      }
      this._listeners.get(evt).add(fn);
      return () => {
        return this.off(evt, fn); // return unsubscribe thunk
      };
    }

    off(evt, fn) {
      var set;
      if (!_isFunction(fn)) {
        return;
      }
      set = this._listeners.get(String(evt));
      if (set != null) {
        set.delete(fn);
      }
    }

    once(evt, fn) {
      var unsub;
      if (!_isFunction(fn)) {
        return;
      }
      unsub = this.on(evt, (payload) => {
        if (typeof unsub === "function") {
          unsub();
        }
        return fn(payload);
      });
      return unsub;
    }

    emit(evt, payload = null) {
      var count, err, fn, fns, l, len, set;
      set = this._listeners.get(String(evt));
      if (!(set != null ? set.size : void 0)) {
        return 0;
      }
      fns = [...set]; // snapshot to avoid mutation during iteration
      count = 0;
      for (l = 0, len = fns.length; l < len; l++) {
        fn = fns[l];
        try {
          fn(payload);
        } catch (error) {
          err = error;
          try {
            console.warn('[EventEmitter] listener error for "%s": %s', evt, err != null ? err.message : void 0);
          } catch (error) {}
        }
        count += 1;
      }
      return count;
    }

    clear(evt = null) {
      if (evt != null) {
        this._listeners.delete(String(evt));
      } else {
        this._listeners.clear();
      }
    }

    listenerCount(evt) {
      var set;
      set = this._listeners.get(String(evt));
      if (set != null) {
        return set.size;
      } else {
        return 0;
      }
    }

  };

  MusicPlayer = (function() {
    // ── MusicPlayer ───────────────────────────────────────────────────────
    class MusicPlayer extends EventEmitter {
      constructor(opts = {}) {
        var ref, ref1;
        super();
        // Bound handler refs — stable references so removeEventListener works
        this._onAudioPlay = this._onAudioPlay.bind(this);
        this._onAudioPause = this._onAudioPause.bind(this);
        this._onAudioWaiting = this._onAudioWaiting.bind(this);
        this._onAudioCanPlay = this._onAudioCanPlay.bind(this);
        this._onAudioEnded = this._onAudioEnded.bind(this);
        this._onAudioError = this._onAudioError.bind(this);
        this._onAudioTimeUpdate = this._onAudioTimeUpdate.bind(this);
        this._onAudioLoadedMetadata = this._onAudioLoadedMetadata.bind(this);
        this._onAudioSeeked = this._onAudioSeeked.bind(this);
        this.logger = _isPlainObject(opts.logger) && _isFunction(opts.logger.debug) && _isFunction(opts.logger.warn) && _isFunction(opts.logger.error) ? opts.logger : console;
        this.state = STATES.IDLE;
        this.queue = [];
        this.queueIndex = 0;
        this.shuffle = false;
        this.repeatMode = REPEAT.OFF;
        this.volume = 0.8;
        this.isMuted = false;
        this.currentTrack = null;
        this.positionSec = 0;
        this.playlistId = null;
        this.playOrder = null;
        this._playOrderMap = null; // reverse map: queueIndex → position in playOrder
        this._lastError = null;
        this._destroyed = false;
        // Crossfade internals
        this._crossfading = false;
        this._crossfadeTimer = null;
        this._pendingAudio = null;
        // Debounced persist
        this._persistTimer = null;
        // Storage backend
        this._storage = (ref = opts.storage) != null ? ref : null;
        // HTML5 Audio element
        this._audio = (ref1 = opts.audioEl) != null ? ref1 : null;
        if ((this._audio == null) && typeof Audio !== 'undefined') {
          try {
            this._audio = new Audio();
          } catch (error) {}
        }
        if (this._audio != null) {
          this._bindAudioEvents(this._audio);
        }
        try {
          // Load persisted preferences
          this._loadPersisted();
        } catch (error) {
          void 0;
        }
        return;
      }

      // ── State read API ──────────────────────────────────────────────────
      isPlaying() {
        return this.state === STATES.PLAYING;
      }

      isPaused() {
        return this.state === STATES.PAUSED;
      }

      isLoading() {
        return this.state === STATES.LOADING || this.state === STATES.BUFFERING;
      }

      getPublicState() {
        var ref;
        return {
          state: this.state,
          queue: this.queue.slice(),
          queueLength: this.queue.length,
          queueIndex: this.queueIndex,
          shuffle: !!this.shuffle,
          repeatMode: this.repeatMode,
          volume: this.volume,
          isMuted: !!this.isMuted,
          currentTrack: this.currentTrack != null ? Object.assign({}, this.currentTrack) : null,
          positionSec: this.positionSec,
          durationSec: this.getDuration(),
          playlistId: (ref = this.playlistId) != null ? ref : null,
          lastError: this._lastError,
          hasAudioDriver: this._audio != null
        };
      }

      getDuration() {
        var d, ref;
        d = Number((ref = this._audio) != null ? ref.duration : void 0);
        if (Number.isFinite(d)) {
          return d;
        } else {
          return 0;
        }
      }

      getBuffered() {
        var a, ref;
        a = this._audio;
        if (!(a != null ? (ref = a.buffered) != null ? ref.length : void 0 : void 0)) {
          return 0;
        }
        try {
          return a.buffered.end(a.buffered.length - 1);
        } catch (error) {
          return 0;
        }
      }

      // ── Persistence ──────────────────────────────────────────────────────
      _storageBackend() {
        if (this._storage != null) {
          return this._storage;
        }
        if (typeof localStorage !== 'undefined') {
          return localStorage;
        } else {
          return null;
        }
      }

      _loadPersisted() {
        var backend, err, obj, raw, ref, ref1, ref2;
        backend = this._storageBackend();
        if (backend == null) {
          return;
        }
        raw = backend.getItem(this.STORAGE_KEY);
        if (!(_isString(raw) && raw.length > 0)) {
          return;
        }
        try {
          obj = JSON.parse(raw);
        } catch (error) {
          err = error;
          if ((ref = this.logger) != null) {
            if (typeof ref.warn === "function") {
              ref.warn('[MusicPlayer._loadPersisted] JSON parse failed', err != null ? err.message : void 0);
            }
          }
          return;
        }
        if (!_isPlainObject(obj)) {
          return;
        }
        this.volume = _clamp((ref1 = Number(obj.volume)) != null ? ref1 : this.volume, 0, 1);
        this.isMuted = !!obj.isMuted;
        this.shuffle = !!obj.shuffle;
        this.repeatMode = (ref2 = obj.repeatMode) === REPEAT.OFF || ref2 === REPEAT.ONE || ref2 === REPEAT.ALL ? String(obj.repeatMode) : REPEAT.OFF;
        this.queue = _isArray(obj.queue) ? obj.queue.slice(0, this.MAX_QUEUE) : [];
        this.queueIndex = _isPositiveInt(obj.queueIndex) && obj.queueIndex < this.queue.length ? obj.queueIndex : 0;
        this.playlistId = _isString(obj.playlistId) && obj.playlistId.length > 0 ? obj.playlistId : null;
        this._rebuildPlayOrder();
      }

      persist() {
        var backend, err, payload;
        if (this._destroyed) {
          return false;
        }
        backend = this._storageBackend();
        if (backend == null) {
          return false;
        }
        payload = {
          volume: this.volume,
          isMuted: this.isMuted,
          shuffle: this.shuffle,
          repeatMode: this.repeatMode,
          queue: this.queue.slice(0, this.MAX_PERSIST_QUEUE),
          queueIndex: this.queueIndex,
          playlistId: this.playlistId,
          savedAt: _nowIso()
        };
        try {
          backend.setItem(this.STORAGE_KEY, JSON.stringify(payload));
          return true;
        } catch (error) {
          err = error;
          this.logger.warn('[MusicPlayer.persist] storage failed', err != null ? err.message : void 0);
          return false;
        }
      }

      _schedulePersist() {
        if (this._destroyed) {
          return;
        }
        if (this._persistTimer != null) {
          clearTimeout(this._persistTimer);
        }
        this._persistTimer = setTimeout((() => {
          return this.persist();
        }), this.PERSIST_DEBOUNCE);
      }

      // ── Audio DOM bindings ──────────────────────────────────────────────
      _bindAudioEvents(a) {
        var err;
        if (a == null) {
          return;
        }
        if (a._mpBound) { // prevent double-binding
          return;
        }
        a._mpBound = true;
        try {
          a.preload = 'metadata';
          a.volume = this.isMuted ? 0 : this.volume;
          a.addEventListener('play', this._onAudioPlay);
          a.addEventListener('pause', this._onAudioPause);
          a.addEventListener('waiting', this._onAudioWaiting);
          a.addEventListener('canplay', this._onAudioCanPlay);
          a.addEventListener('ended', this._onAudioEnded);
          a.addEventListener('error', this._onAudioError);
          a.addEventListener('timeupdate', this._onAudioTimeUpdate);
          a.addEventListener('loadedmetadata', this._onAudioLoadedMetadata);
          a.addEventListener('seeked', this._onAudioSeeked);
        } catch (error) {
          err = error;
          this.logger.warn('[MusicPlayer._bindAudioEvents] binding failed', err != null ? err.message : void 0);
        }
      }

      _unbindAudioEvents(a) {
        if (!((a != null) && a._mpBound)) {
          return;
        }
        a._mpBound = false;
        try {
          a.removeEventListener('play', this._onAudioPlay);
          a.removeEventListener('pause', this._onAudioPause);
          a.removeEventListener('waiting', this._onAudioWaiting);
          a.removeEventListener('canplay', this._onAudioCanPlay);
          a.removeEventListener('ended', this._onAudioEnded);
          a.removeEventListener('error', this._onAudioError);
          a.removeEventListener('timeupdate', this._onAudioTimeUpdate);
          a.removeEventListener('loadedmetadata', this._onAudioLoadedMetadata);
          a.removeEventListener('seeked', this._onAudioSeeked);
        } catch (error) {
          void 0;
        }
      }

      _onAudioPlay() {
        boundMethodCheck(this, MusicPlayer);
        if (this._crossfading) {
          return;
        }
        return this._transition(STATES.PLAYING, {
          driver: 'audio'
        });
      }

      _onAudioPause() {
        boundMethodCheck(this, MusicPlayer);
        if (this._crossfading) {
          return;
        }
        return this._transition(STATES.PAUSED, {
          driver: 'audio'
        });
      }

      _onAudioWaiting() {
        boundMethodCheck(this, MusicPlayer);
        if (this._crossfading) {
          return;
        }
        return this._transition(STATES.BUFFERING, {
          driver: 'audio'
        });
      }

      _onAudioCanPlay() {
        var a;
        boundMethodCheck(this, MusicPlayer);
        if (this._crossfading) {
          return;
        }
        a = this._audio;
        if (a == null) {
          return;
        }
        return this._transition((a.paused ? STATES.PAUSED : STATES.PLAYING), {
          driver: 'audio'
        });
      }

      _onAudioEnded() {
        boundMethodCheck(this, MusicPlayer);
        if (this._crossfading) {
          return;
        }
        this._transition(STATES.ENDED, {
          driver: 'audio'
        });
        return this.next(true);
      }

      _onAudioError(e) {
        var code, msg, ref, ref1, ref2, ref3, ref4, ref5;
        boundMethodCheck(this, MusicPlayer);
        if (this._crossfading) {
          return;
        }
        code = (ref = e != null ? (ref1 = e.target) != null ? (ref2 = ref1.error) != null ? ref2.code : void 0 : void 0 : void 0) != null ? ref : 'unknown';
        msg = (ref3 = e != null ? (ref4 = e.target) != null ? (ref5 = ref4.error) != null ? ref5.message : void 0 : void 0 : void 0) != null ? ref3 : '';
        this._lastError = `AUDIO_ERROR:${code}`;
        return this._transition(STATES.ERROR, {
          driver: 'audio',
          error: this._lastError,
          detail: msg
        });
      }

      _onAudioTimeUpdate() {
        var a, sec;
        boundMethodCheck(this, MusicPlayer);
        try {
          a = this._audio;
          if (a == null) {
            return;
          }
          sec = Number(a.currentTime);
          this.positionSec = Number.isFinite(sec) ? _clamp(sec, 0, 2e308) : 0;
          return this.emit('position', {
            positionSec: this.positionSec,
            durationSec: this.getDuration()
          });
        } catch (error) {
          return void 0;
        }
      }

      _onAudioLoadedMetadata() {
        boundMethodCheck(this, MusicPlayer);
        return this.emit('duration', {
          durationSec: this.getDuration()
        });
      }

      _onAudioSeeked() {
        var a, sec;
        boundMethodCheck(this, MusicPlayer);
        try {
          a = this._audio;
          if (a == null) {
            return;
          }
          sec = Number(a.currentTime);
          this.positionSec = Number.isFinite(sec) ? _clamp(sec, 0, 2e308) : 0;
          return this.emit('seeked', {
            positionSec: this.positionSec,
            durationSec: this.getDuration()
          });
        } catch (error) {
          return void 0;
        }
      }

      // ── Swap audio element (used by crossfade) ──────────────────────────
      _swapAudio(newAudio) {
        var old;
        old = this._audio;
        if (old != null) {
          this._unbindAudioEvents(old);
        }
        try {
          if (old != null) {
            old.pause();
          }
        } catch (error) {}
        try {
          if (old != null) {
            old.removeAttribute('src');
          }
        } catch (error) {}
        try {
          if (old != null) {
            old.load(); // release held network resources
          }
        } catch (error) {}
        this._audio = newAudio;
        this._bindAudioEvents(newAudio);
      }

      // ── Internal state transitions ──────────────────────────────────────
      _transition(next, meta = null) {
        var allowed, prev, ref;
        if (this._destroyed) {
          return;
        }
        prev = this.state;
        // Suppress audio-driven duplicates; allow explicit re-emission
        if (prev === next && (meta != null ? meta.driver : void 0) === 'audio') {
          return;
        }
        // Soft validation — warn on unexpected transitions but don't block
        allowed = VALID_TRANSITIONS[prev];
        if ((allowed != null) && indexOf.call(allowed, next) < 0 && !(meta != null ? meta.force : void 0)) {
          if ((ref = this.logger) != null) {
            if (typeof ref.warn === "function") {
              ref.warn('[MusicPlayer._transition] unexpected %s → %s', prev, next);
            }
          }
        }
        this.state = next;
        this._schedulePersist();
        this.emit('state', {
          previous: prev,
          state: next,
          meta: meta,
          currentTrack: this.currentTrack,
          positionSec: this.positionSec,
          queueIndex: this.queueIndex
        });
      }

      // ── Track URL resolution (DRY) ──────────────────────────────────────
      _resolveTrackUrl(track) {
        var ref, ref1, ref2;
        if (!_isPlainObject(track)) {
          return null;
        }
        return (ref = (ref1 = (ref2 = track.streamUrl) != null ? ref2 : track.url) != null ? ref1 : track.localPath) != null ? ref : null;
      }

      // ── Track loading & playback controls ───────────────────────────────
      loadTrack(track) {
        var err, ref, url;
        if (!(_isPlainObject(track) && _isString(track.title))) {
          throw new TypeError('loadTrack requires track object with title');
        }
        this._cancelCrossfade();
        this._setTrackInternal(track);
        if (this._audio != null) {
          url = this._resolveTrackUrl(track);
          if (url != null) {
            this._transition(STATES.LOADING);
            try {
              this._audio.pause();
              this._audio.src = url;
              this._audio.load();
            } catch (error) {
              err = error;
              this._lastError = `LOAD_FAILED: ${(ref = err != null ? err.message : void 0) != null ? ref : 'unknown'}`;
              this._transition(STATES.ERROR, {
                error: this._lastError
              });
            }
          } else {
            this.positionSec = 0;
            this._transition(STATES.PAUSED);
          }
        } else {
          this.positionSec = 0;
          this._transition(STATES.PAUSED);
        }
        this.emit('track', Object.assign({}, this.currentTrack));
        return this.currentTrack;
      }

      play() {
        var err, p, ref, ref1;
        if (this._destroyed) {
          return false;
        }
        if (this.currentTrack == null) {
          if (this.queue.length > 0) {
            this._playIndex((ref = this.queueIndex) != null ? ref : 0);
            return true;
          }
          return false;
        }
        if (this._audio != null) {
          try {
            p = this._audio.play();
            if ((p != null) && _isFunction(p.then)) {
              p.catch((err) => {
                var ref1;
                this._lastError = `PLAY_REJECTED: ${(ref1 = err != null ? err.message : void 0) != null ? ref1 : 'autoplay blocked'}`;
                return this._transition(STATES.ERROR, {
                  error: this._lastError
                });
              });
            }
          } catch (error) {
            err = error;
            this._lastError = `PLAY_FAILED: ${(ref1 = err != null ? err.message : void 0) != null ? ref1 : 'unknown'}`;
            this._transition(STATES.ERROR, {
              error: this._lastError
            });
          }
        } else {
          this._transition(STATES.PLAYING);
        }
        return true;
      }

      pause() {
        var ref;
        if (this._destroyed) {
          return false;
        }
        this._cancelCrossfade();
        try {
          if ((ref = this._audio) != null) {
            ref.pause();
          }
        } catch (error) {}
        this._transition(STATES.PAUSED);
        return true;
      }

      toggle() {
        if (this.state === STATES.PLAYING) {
          return this.pause();
        } else {
          return this.play();
        }
      }

      stop() {
        var ref;
        if (this._destroyed) {
          return false;
        }
        this._cancelCrossfade();
        try {
          if ((ref = this._audio) != null) {
            ref.pause();
          }
          if (this._audio != null) {
            this._audio.currentTime = 0;
          }
        } catch (error) {
          void 0;
        }
        this.positionSec = 0;
        this._transition(STATES.IDLE);
        return true;
      }

      seek(seconds) {
        var ref, sec, wasPlaying;
        wasPlaying = this.state === STATES.PLAYING;
        this._cancelCrossfade();
        sec = _isNumber(seconds) ? _clamp(seconds, 0, 2e308) : 0;
        this.positionSec = sec;
        if (this._audio != null) {
          try {
            if (Number.isFinite(this._audio.duration)) {
              sec = _clamp(sec, 0, this._audio.duration);
            }
            this._audio.currentTime = sec;
          } catch (error) {
            void 0;
          }
        }
        this.emit('position', {
          positionSec: sec,
          durationSec: this.getDuration()
        });
        
        // Resume playback if it was interrupted by crossfade cancellation
        if (wasPlaying && ((ref = this._audio) != null ? ref.paused : void 0)) {
          this.play();
        }
        return sec;
      }

      setVolume(vol) {
        var v;
        v = _clamp(Number(vol != null ? vol : 0), 0, 1);
        this.volume = v;
        if ((this._audio != null) && !this.isMuted) {
          try {
            this._audio.volume = v;
          } catch (error) {}
        }
        this._schedulePersist();
        this.emit('volume', {
          volume: v,
          isMuted: this.isMuted
        });
        return v;
      }

      volumeUp(step = this.VOLUME_STEP) {
        return this.setVolume(this.volume + step);
      }

      volumeDown(step = this.VOLUME_STEP) {
        return this.setVolume(this.volume - step);
      }

      muteToggle(force = null) {
        this.isMuted = force != null ? !!force : !this.isMuted;
        if (this._audio != null) {
          try {
            this._audio.volume = this.isMuted ? 0 : this.volume;
          } catch (error) {}
        }
        this._schedulePersist();
        this.emit('volume', {
          volume: this.volume,
          isMuted: this.isMuted
        });
        return this.isMuted;
      }

      // ── Queue management ────────────────────────────────────────────────
      _emitQueueChange() {
        return this.emit('queue', {
          queue: this.queue.slice(),
          index: this.queueIndex,
          playlistId: this.playlistId
        });
      }

      setQueue(tracks, startIndex = 0, playlistId = null) {
        if (!_isArray(tracks)) {
          throw new TypeError('setQueue expects array');
        }
        this.queue = tracks.filter(function(t) {
          return _isPlainObject(t);
        }).slice(0, this.MAX_QUEUE);
        this.playlistId = _isString(playlistId) && playlistId.length > 0 ? playlistId : null;
        this.queueIndex = _clamp(parseInt(startIndex, 10) || 0, 0, Math.max(0, this.queue.length - 1));
        this._rebuildPlayOrder();
        this._schedulePersist();
        this._emitQueueChange();
        return this.queue.length;
      }

      enqueue(track, front = false) {
        var ref;
        if (!_isPlainObject(track)) {
          throw new TypeError('enqueue expects track object');
        }
        if (this.queue.length >= this.MAX_QUEUE) {
          if ((ref = this.logger) != null) {
            if (typeof ref.warn === "function") {
              ref.warn('[MusicPlayer.enqueue] queue at max capacity (%d)', this.MAX_QUEUE);
            }
          }
          return this.queue.length;
        }
        if (front) {
          this.queue.unshift(track);
          this.queueIndex = 0;
        } else {
          this.queue.push(track);
        }
        this._rebuildPlayOrder();
        this._schedulePersist();
        this._emitQueueChange();
        return this.queue.length;
      }

      clearQueue() {
        this.queue = [];
        this.queueIndex = 0;
        this.playlistId = null;
        this.playOrder = null;
        this._playOrderMap = null;
        this._schedulePersist();
        this._emitQueueChange();
        return 0;
      }

      reorderQueue(fromIndex, toIndex) {
        var from, item, ref, ref1, to;
        from = parseInt(fromIndex, 10);
        to = parseInt(toIndex, 10);
        if (!(Number.isFinite(from) && Number.isFinite(to) && (0 <= from && from < this.queue.length) && (0 <= to && to <= this.queue.length))) {
          return this.queue;
        }
        [item] = this.queue.splice(from, 1);
        this.queue.splice(to, 0, item);
        // Adjust queueIndex to keep pointing at the same logical track
        if (from === this.queueIndex) {
          this.queueIndex = to;
        } else if ((from < (ref = this.queueIndex) && ref <= to)) {
          this.queueIndex -= 1;
        } else if ((to <= (ref1 = this.queueIndex) && ref1 < from)) {
          this.queueIndex += 1;
        }
        this._rebuildPlayOrder();
        this._schedulePersist();
        this._emitQueueChange();
        return this.queue.slice();
      }

      removeFromQueue(index) {
        var i, removed;
        i = parseInt(index, 10);
        if (!(Number.isFinite(i) && (0 <= i && i < this.queue.length))) {
          return null;
        }
        [removed] = this.queue.splice(i, 1);
        if (i < this.queueIndex) {
          this.queueIndex = Math.max(0, this.queueIndex - 1);
        } else if (i === this.queueIndex) {
          this.queueIndex = Math.min(this.queueIndex, Math.max(0, this.queue.length - 1));
        }
        this._rebuildPlayOrder();
        this._schedulePersist();
        this._emitQueueChange();
        return removed;
      }

      // ── Shuffle / repeat ────────────────────────────────────────────────
      _rebuildPlayOrder() {
        var ref;
        if (!this.shuffle) {
          this.playOrder = null;
          this._playOrderMap = null;
          return;
        }
        this.playOrder = _shuffleArr((function() {
          var results = [];
          for (var l = 0, ref = this.queue.length; 0 <= ref ? l < ref : l > ref; 0 <= ref ? l++ : l--){ results.push(l); }
          return results;
        }).apply(this));
        this._playOrderMap = new Map();
        this.playOrder.forEach((idx, pos) => {
          return this._playOrderMap.set(idx, pos);
        });
      }

      setShuffle(enabled) {
        this.shuffle = !!enabled;
        this._rebuildPlayOrder();
        this._schedulePersist();
        this._emitQueueChange();
        return this.shuffle;
      }

      setRepeat(mode) {
        var m;
        m = String(mode != null ? mode : REPEAT.OFF).toLowerCase();
        this.repeatMode = m === REPEAT.OFF || m === REPEAT.ONE || m === REPEAT.ALL ? m : REPEAT.OFF;
        this._schedulePersist();
        this.emit('repeat', {
          mode: this.repeatMode
        });
        return this.repeatMode;
      }

      // ── Previous / Next ─────────────────────────────────────────────────
      next(auto = false) {
        var nextIdx;
        if (this._destroyed) {
          return false;
        }
        if (this.repeatMode === REPEAT.ONE && auto && this.queue.length > 0) {
          this.seek(0);
          this.play();
          return true;
        }
        if (this.queue.length === 0) {
          return false;
        }
        nextIdx = this._resolveNextIndex();
        if (nextIdx < 0) {
          return this._finishQueue();
        }
        this._playIndex(nextIdx);
        return true;
      }

      previous() {
        if (this._destroyed) {
          return false;
        }
        if (!(this.queue.length > 0)) {
          return false;
        }
        // Standard UX: restart current track if past threshold, otherwise go back
        if (this.positionSec > this.RESTART_THRESHOLD) {
          this.seek(0);
          return true;
        }
        this._playIndex(this._resolvePrevIndex());
        return true;
      }

      _resolveNextIndex() {
        var flatIdx, ref, ref1;
        if (this.playOrder != null) {
          flatIdx = (ref = (ref1 = this._playOrderMap) != null ? ref1.get(this.queueIndex) : void 0) != null ? ref : -1;
          if (flatIdx < 0) {
            return 0;
          }
          if (flatIdx + 1 < this.playOrder.length) {
            return this.playOrder[flatIdx + 1];
          }
          if (this.repeatMode === REPEAT.ALL) {
            return this.playOrder[0];
          } else {
            return -1;
          }
        }
        if (this.queueIndex + 1 < this.queue.length) {
          return this.queueIndex + 1;
        } else if (this.repeatMode === REPEAT.ALL) {
          return 0;
        } else {
          return -1;
        }
      }

      _resolvePrevIndex() {
        var flatIdx, ref, ref1;
        if (this.playOrder != null) {
          flatIdx = (ref = (ref1 = this._playOrderMap) != null ? ref1.get(this.queueIndex) : void 0) != null ? ref : -1;
          if (flatIdx < 0) {
            return this.queueIndex;
          }
          if (flatIdx > 0) {
            return this.playOrder[flatIdx - 1];
          }
          // At start of shuffled queue
          if (this.repeatMode === REPEAT.ALL) {
            return this.playOrder[this.playOrder.length - 1];
          } else {
            return this.playOrder[0];
          }
        }
        return Math.max(0, this.queueIndex - 1);
      }

      _playIndex(i) {
        var idx, nextTrack;
        idx = _clamp(parseInt(i, 10) || 0, 0, Math.max(0, this.queue.length - 1));
        this.queueIndex = idx;
        nextTrack = this.queue[idx];
        if (nextTrack == null) {
          return null;
        }
        this._schedulePersist();
        if (this.state === STATES.PLAYING && this.CROSSFADE_MS > 0 && (this._audio != null)) {
          this._crossfade(nextTrack);
        } else {
          this.loadTrack(nextTrack);
          this.play();
        }
        return nextTrack;
      }

      // ── Crossfade ───────────────────────────────────────────────────────
      _crossfade(nextTrack) {
        var aborted, fail, finish, oldAudio, pending, phase, phaseStep, startVol, stepMs, steps, url, waitingForPlay;
        this._cancelCrossfade();
        url = this._resolveTrackUrl(nextTrack);
        if (url == null) {
          this.loadTrack(nextTrack);
          this.play();
          return;
        }
        // Prepare the new audio element
        pending = null;
        if (typeof Audio !== 'undefined') {
          try {
            pending = new Audio();
          } catch (error) {}
        }
        if (pending == null) {
          this.loadTrack(nextTrack);
          this.play();
          return;
        }
        pending.volume = 0;
        pending.src = url;
        pending.preload = 'auto';
        pending.load();
        this._crossfading = true;
        this._pendingAudio = pending;
        oldAudio = this._audio;
        startVol = this.isMuted ? 0 : this.volume;
        steps = 10;
        stepMs = Math.max(1, Math.floor(this.CROSSFADE_MS / (steps * 2)));
        phase = 'out';
        phaseStep = 0;
        waitingForPlay = false;
        aborted = false; // guard against double-finish
        
        // ── Successful crossfade completion ──────────────────────────────
        finish = () => {
          if (aborted) {
            return;
          }
          aborted = true;
          if (this._crossfadeTimer != null) {
            clearInterval(this._crossfadeTimer);
            this._crossfadeTimer = null;
          }
          this._crossfading = false;
          this._pendingAudio = null;
          this._swapAudio(pending);
          this._setTrackInternal(nextTrack);
          try {
            pending.volume = this.isMuted ? 0 : this.volume;
          } catch (error) {}
          this._transition(STATES.PLAYING);
          return this.emit('crossfade', {
            done: true
          });
        };
        // ── Crossfade failure (e.g. play() rejected) ────────────────────
        fail = (reason) => {
          if (aborted) {
            return;
          }
          aborted = true;
          if (this._crossfadeTimer != null) {
            clearInterval(this._crossfadeTimer);
            this._crossfadeTimer = null;
          }
          this._crossfading = false;
          this._pendingAudio = null;
          try {
            // Clean up the audio that failed to play
            pending.pause();
          } catch (error) {}
          try {
            pending.removeAttribute('src');
          } catch (error) {}
          try {
            pending.load();
          } catch (error) {}
          // Restore old audio volume if it's still active
          if ((oldAudio != null) && !this.isMuted) {
            try {
              oldAudio.volume = startVol;
            } catch (error) {}
          }
          this._lastError = `CROSSFADE_FAILED: ${reason != null ? reason : 'unknown'}`;
          this._transition(STATES.ERROR, {
            error: this._lastError
          });
          return this.emit('crossfade', {
            done: false,
            error: this._lastError
          });
        };
        this._crossfadeTimer = setInterval(() => {
          var err, playResult, tgt;
          // Bail out if waiting for async play promise or destroyed
          if (aborted || waitingForPlay || this._destroyed || !this._crossfading) {
            return;
          }
          try {
            if (phase === 'out') {
              phaseStep += 1;
              try {
                if (!this.isMuted) {
                  oldAudio.volume = Math.max(0, startVol * (1 - phaseStep / steps));
                }
              } catch (error) {}
              if (phaseStep >= steps) {
                try {
                  oldAudio.pause();
                } catch (error) {}
                playResult = pending.play();
                if ((playResult != null) && _isFunction(playResult.then)) {
                  waitingForPlay = true;
                  return playResult.then(() => {
                    // Ignore if crossfade was cancelled while waiting
                    if (!(this._crossfading && this._pendingAudio === pending)) {
                      return;
                    }
                    waitingForPlay = false;
                    phase = 'in';
                    return phaseStep = 0;
                  }).catch((err) => {
                    var ref;
                    if (!(this._crossfading && this._pendingAudio === pending)) {
                      return;
                    }
                    return fail(`PLAY_REJECTED: ${(ref = err != null ? err.message : void 0) != null ? ref : 'autoplay'}`);
                  });
                } else {
                  phase = 'in';
                  return phaseStep = 0; // phase is 'in'
                }
              }
            } else {
              phaseStep += 1;
              tgt = this.isMuted ? 0 : this.volume;
              try {
                pending.volume = tgt * (phaseStep / steps);
              } catch (error) {}
              if (phaseStep >= steps) {
                return finish();
              }
            }
          } catch (error) {
            err = error;
            this.logger.warn('[MusicPlayer.crossfade] step failed', err != null ? err.message : void 0);
            return fail(err != null ? err.message : void 0);
          }
        }, stepMs);
      }

      _cancelCrossfade() {
        var pending;
        if (this._crossfadeTimer != null) {
          clearInterval(this._crossfadeTimer);
          this._crossfadeTimer = null;
        }
        pending = this._pendingAudio;
        if (pending != null) {
          try {
            pending.pause();
          } catch (error) {}
          try {
            pending.removeAttribute('src');
          } catch (error) {}
          try {
            pending.load();
          } catch (error) {}
          this._pendingAudio = null;
        }
        if (this._crossfading && (this._audio != null)) {
          // Restore volume if not muted
          if (!this.isMuted) {
            try {
              this._audio.volume = this.volume;
            } catch (error) {}
          }
        }
        this._crossfading = false;
      }

      // ── Queue end ───────────────────────────────────────────────────────
      _finishQueue() {
        var ref;
        try {
          if ((ref = this._audio) != null) {
            ref.pause();
          }
        } catch (error) {}
        this._transition(STATES.ENDED, {
          finished: true
        });
        return false;
      }

      // ── Internal setter ─────────────────────────────────────────────────
      _setTrackInternal(t) {
        var flat, k, ref, v;
        flat = {};
        for (k in t) {
          v = t[k];
          if (v !== void 0) {
            flat[k] = v;
          }
        }
        flat.sourceType = (ref = t.sourceType) != null ? ref : 'unknown';
        flat.title = _isString(t.title) && t.title.length > 0 ? t.title : 'Untitled';
        this.currentTrack = Object.freeze(flat);
        this.positionSec = 0;
        this._lastError = null;
        return this.currentTrack;
      }

      // ── Destroy ─────────────────────────────────────────────────────────
      destroy() {
        if (this._destroyed) {
          return;
        }
        this._destroyed = true;
        this._cancelCrossfade();
        try {
          if (this._audio != null) {
            this._unbindAudioEvents(this._audio);
            this._audio.pause();
            this._audio.removeAttribute('src');
            this._audio.load();
          }
        } catch (error) {
          void 0;
        }
        if (this._persistTimer != null) {
          clearTimeout(this._persistTimer);
          this._persistTimer = null;
        }
        this.clear();
      }

    };

    // Class-level enum access — no instance needed
    MusicPlayer.STATES = STATES;

    MusicPlayer.REPEAT = REPEAT;

    MusicPlayer.prototype.CROSSFADE_MS = 5000;

    MusicPlayer.prototype.PERSIST_DEBOUNCE = 300;

    MusicPlayer.prototype.STORAGE_KEY = 'helpy.musicplayer.state.v1';

    MusicPlayer.prototype.VOLUME_STEP = 0.05;

    MusicPlayer.prototype.MAX_QUEUE = 10000;

    MusicPlayer.prototype.MAX_PERSIST_QUEUE = 1000;

    MusicPlayer.prototype.RESTART_THRESHOLD = 3; // seconds before 'previous' restarts current track

    return MusicPlayer;

  }).call(this);

  module.exports = {
    MusicPlayer: MusicPlayer,
    EventEmitter: EventEmitter,
    STATES: STATES,
    REPEAT: REPEAT
  };

}).call(this);
