// Generated by CoffeeScript 2.7.0
(function() {
  /*
   * SecurityManager — Authenticated encryption (AES-GCM/CBC), scrypt password
   * hashing, JWT algorithm pinning, sliding-window rate limiting, HMAC utilities,
   * and helpers for secure storage and safe logging.
   *
   * Constructor options:
   *   secretKey         — Buffer or hex string of correct length (auto-generated
   *                        if falsy; non-hex strings derived via scrypt with caveats)
   *   logger            — optional { debug, info, warn, error } logger object
   *   scryptOptions     — { N, r, p } for scrypt (defaults: N=16384, r=8, p=1)
   *   algorithm         — cipher algorithm (default 'aes-256-gcm')
   *   ivLength          — override IV bytes (default: 12 for GCM, 16 for CBC)
   *   saltLength        — scrypt salt bytes (default 16)
   *   scryptKeyLength   — scrypt output bytes (default 64)
   *   legacyHmacKey     — set true to decrypt CBC data created by v1.x which used
   *                        SHA-256(label‖key) instead of HMAC-SHA256(key, label)
   *   redactInspect     — hide algorithm name from inspect()/toJSON() (default true)
   */
  var BASE64_RE, CSRFTokenError, DEFAULT_SCRYPT_OPTIONS, DecryptionError, EncryptionError, GCM_RE, HEX_EVEN_RE, HMAC_KEY_LABEL, HashingError, KEY_LENGTHS, KeyLengthError, PASSPHRASE_SALT, RateLimitError, SENSITIVE_RE, SUPPORTED_ALGORITHMS, SecurityError, SecurityManager, _jwtLoader, coerceKey, constantTimeCompare, crypto, isBuffer, isFunction, isGCM, isNonEmptyString, isPlainObject, isPositiveInt, isString, ivLengthFor, keyLengthFor, mergeScryptOpts, parseSalt, promisify, scryptAsync, validateScryptOpts, zeroBuffer,
    hasProp = {}.hasOwnProperty;

  crypto = require('crypto');

  ({promisify} = require('util'));

  scryptAsync = promisify(crypto.scrypt);

  // ── Lazy-loaded optional dependency ──────────────────────────────────────────
  _jwtLoader = function() {
    try {
      return require('jsonwebtoken');
    } catch (error) {
      return null;
    }
  };

  // ── Type guards ──────────────────────────────────────────────────────────────
  isString = function(v) {
    return typeof v === 'string';
  };

  isNonEmptyString = function(v) {
    return isString(v) && v.length > 0;
  };

  isBuffer = function(v) {
    return Buffer.isBuffer(v);
  };

  isPlainObject = function(v) {
    return (v != null) && typeof v === 'object' && !Array.isArray(v);
  };

  isPositiveInt = function(v) {
    return Number.isInteger(v) && v > 0;
  };

  isFunction = function(v) {
    return typeof v === 'function';
  };

  // Even-length hex only — prevents silent truncation by Buffer.from(_, 'hex')
  HEX_EVEN_RE = /^(?:[0-9a-fA-F]{2})+$/;

  BASE64_RE = /^[A-Za-z0-9+\/]+={0,2}$/;

  GCM_RE = /gcm/i;

  // Pre-compiled sensitive-key regex (compiled once, reused per walk)
  SENSITIVE_RE = /(?:password|passwd|pwd|secret|token|api[_-]?key|private[_-]?key|jwt|session|cookie|auth|credential|ssn|social[_-]?sec|credit[_-]?card|card[_-]?num|cvv|access[_-]?code|pin|bearer)/i;

  // ── Error classes ────────────────────────────────────────────────────────────
  SecurityError = class SecurityError extends Error {
    constructor(msg = 'Security error', cause = null) {
      super(msg);
      this.name = this.constructor.name;
      if (cause != null) {
        this.cause = cause;
      }
      if (typeof Error.captureStackTrace === "function") {
        Error.captureStackTrace(this, this.constructor);
      }
    }

  };

  EncryptionError = class EncryptionError extends SecurityError {
    constructor(msg = 'Encryption failed', cause = null) {
      super(msg, cause);
    }

  };

  DecryptionError = class DecryptionError extends SecurityError {
    constructor(msg = 'Decryption failed', cause = null) {
      super(msg, cause);
    }

  };

  HashingError = class HashingError extends SecurityError {
    constructor(msg = 'Hashing failed', cause = null) {
      super(msg, cause);
    }

  };

  KeyLengthError = class KeyLengthError extends SecurityError {
    constructor(expected, actual) {
      super(`Invalid key length: expected ${expected} bytes, got ${actual}`);
    }

  };

  CSRFTokenError = class CSRFTokenError extends SecurityError {
    constructor(msg = 'Invalid or missing CSRF token') {
      super(msg);
    }

  };

  RateLimitError = class RateLimitError extends SecurityError {
    constructor(key, retryMs) {
      super(isPositiveInt(retryMs) ? `Rate limit exceeded for '${key}'. Retry after ${retryMs} ms.` : `Rate limit exceeded for '${key}'.`);
      this.retryAfterMs = retryMs;
    }

  };

  // ── Algorithm / key utilities ────────────────────────────────────────────────
  SUPPORTED_ALGORITHMS = Object.freeze(new Set(['aes-128-gcm', 'aes-192-gcm', 'aes-256-gcm', 'aes-128-cbc', 'aes-192-cbc', 'aes-256-cbc']));

  KEY_LENGTHS = {
    128: 16,
    192: 24,
    256: 32
  };

  isGCM = function(algo) {
    return GCM_RE.test(algo);
  };

  keyLengthFor = function(algo) {
    var ref, ref1;
    return (ref = KEY_LENGTHS[(ref1 = /^aes-(\d+)-/.exec(algo)) != null ? ref1[1] : void 0]) != null ? ref : 32;
  };

  ivLengthFor = function(algo) {
    if (isGCM(algo)) {
      return 12;
    } else {
      return 16;
    }
  };

  DEFAULT_SCRYPT_OPTIONS = Object.freeze({
    N: 16384,
    r: 8,
    p: 1
  });

  HMAC_KEY_LABEL = 'SecurityManager-HMAC-Key-Derivation';

  PASSPHRASE_SALT = Buffer.from('53656375726974794d616e61676572204b65792044657269766174696f6e2053616c74', 'hex');

  // ── Small shared helpers ─────────────────────────────────────────────────────
  validateScryptOpts = function(opts = {}) {
    var N, p, r;
    ({N, r, p} = opts);
    if (!(isPositiveInt(N) && N >= 2 && (N & (N - 1)) === 0)) {
      throw new HashingError(`scrypt N must be a power of 2 ≥ 2; got ${N}`);
    }
    if (!isPositiveInt(r)) {
      throw new HashingError(`scrypt r must be a positive integer; got ${r}`);
    }
    if (!isPositiveInt(p)) {
      throw new HashingError(`scrypt p must be a positive integer; got ${p}`);
    }
  };

  mergeScryptOpts = function(overrides = {}) {
    return {...DEFAULT_SCRYPT_OPTIONS, ...(isPlainObject(overrides) ? overrides : {})};
  };

  parseSalt = function(salt, defaultLength = 16) {
    if (isBuffer(salt)) {
      return salt;
    }
    if (isNonEmptyString(salt) && HEX_EVEN_RE.test(salt)) {
      return Buffer.from(salt, 'hex');
    }
    return crypto.randomBytes(defaultLength);
  };

  coerceKey = function(secretKey, keyLen, logger) {
    var buf;
    if (isBuffer(secretKey)) {
      if (secretKey.length === keyLen) {
        return secretKey;
      }
      throw new KeyLengthError(keyLen, secretKey.length);
    }
    if (isNonEmptyString(secretKey)) {
      if (HEX_EVEN_RE.test(secretKey)) {
        buf = Buffer.from(secretKey, 'hex');
        if (buf.length === keyLen) {
          return buf;
        }
        throw new KeyLengthError(keyLen, buf.length);
      }
      if (logger != null) {
        if (typeof logger.warn === "function") {
          logger.warn('[SecurityManager] Warning: passphrase-derived key — provide proper hex key for production');
        }
      }
      return crypto.scryptSync(secretKey, PASSPHRASE_SALT, keyLen, DEFAULT_SCRYPT_OPTIONS);
    }
    if (logger != null) {
      if (typeof logger.warn === "function") {
        logger.warn('[SecurityManager] No secretKey provided — ephemeral key generated (not persistable across restarts)');
      }
    }
    return crypto.randomBytes(keyLen);
  };

  // Constant-time comparison with length smoothing.
  constantTimeCompare = function(bufA, bufB) {
    if (bufA.length !== bufB.length) {
      crypto.timingSafeEqual(bufA, bufA);
      return false;
    }
    return crypto.timingSafeEqual(bufA, bufB);
  };

  // Zero-fill a Buffer defensively (no-op on null/undefined).
  zeroBuffer = function(buf) {
    if (buf == null) {
      return;
    }
    try {
      buf.fill(0);
    } catch (error) {}
  };

  SecurityManager = (function() {
    // ── SecurityManager ─────────────────────────────────────────────────────────
    class SecurityManager {
      // ── Static: key derivation ─────────────────────────────────────────────────
      static deriveKeyFromPassphrase(passphrase, salt = null, scryptOpts = {}, keyLength = 32) {
        return this._deriveKey('deriveKeyFromPassphrase', passphrase, salt, scryptOpts, keyLength, false);
      }

      static deriveKeyFromPassphraseSync(passphrase, salt = null, scryptOpts = {}, keyLength = 32) {
        return this._deriveKey('deriveKeyFromPassphraseSync', passphrase, salt, scryptOpts, keyLength, true);
      }

      static async _deriveKey(fnName, passphrase, salt, scryptOpts, keyLength, sync) {
        var derived, merged, saltBuf;
        if (!isNonEmptyString(passphrase)) {
          throw new HashingError(`${fnName}: passphrase must be a non-empty string`);
        }
        if (!isPositiveInt(keyLength)) {
          throw new HashingError(`${fnName}: keyLength must be a positive integer`);
        }
        merged = mergeScryptOpts(scryptOpts);
        validateScryptOpts(merged);
        saltBuf = parseSalt(salt);
        derived = sync ? crypto.scryptSync(passphrase, saltBuf, keyLength, merged) : (await scryptAsync(passphrase, saltBuf, keyLength, merged));
        return {
          key: derived.toString('hex'),
          salt: saltBuf.toString('hex')
        };
      }

      static generateKey(bytes = 32) {
        var n;
        n = isPositiveInt(bytes) ? bytes : 32;
        return crypto.randomBytes(n).toString('hex');
      }

      static secureCompare(a, b) {
        var bufA, bufB;
        if (!((isString(a) || isBuffer(a)) && (isString(b) || isBuffer(b)))) {
          return false;
        }
        bufA = isBuffer(a) ? a : Buffer.from(a, 'utf8');
        bufB = isBuffer(b) ? b : Buffer.from(b, 'utf8');
        return constantTimeCompare(bufA, bufB);
      }

      // ── Constructor ────────────────────────────────────────────────────────────
      constructor(secretKey, opts = {}) {
        var err, ref;
        opts = isPlainObject(opts) ? opts : {};
        this._initAlgorithm(opts);
        this._initScrypt(opts);
        this._legacyHmacKey = opts.legacyHmacKey === true;
        this._redactInspect = (ref = opts.redactInspect) != null ? ref : true;
        this._configureLogger(opts.logger);
        this._warnIfUnsupportedAlgo();
        try {
          this.keyBuffer = coerceKey(secretKey, this.aesKeyLength, this.logger);
        } catch (error) {
          err = error;
          this.logger.error('[SecurityManager] key validation failed:', err != null ? err.message : void 0);
          throw err;
        }
        this._hmacKeyBuf = null;
        this._rateLimitBuckets = new Map();
        this._destroyed = false;
        this._inflightAsync = 0;
      }

      _initAlgorithm(opts) {
        var algo;
        algo = isNonEmptyString(opts.algorithm) ? opts.algorithm.toLowerCase() : 'aes-256-gcm';
        this._algorithm = algo;
        this._aesKeyLength = keyLengthFor(algo);
        this._isGCM = isGCM(algo);
        return this._ivLength = isPositiveInt(opts.ivLength) ? opts.ivLength : ivLengthFor(algo);
      }

      _initScrypt(opts) {
        this._saltLength = isPositiveInt(opts.saltLength) ? opts.saltLength : 16;
        this._scryptKeyLength = isPositiveInt(opts.scryptKeyLength) ? opts.scryptKeyLength : 64;
        this._scryptOptions = mergeScryptOpts(opts.scryptOptions);
        return validateScryptOpts(this._scryptOptions);
      }

      _warnIfUnsupportedAlgo() {
        var ref;
        if (SUPPORTED_ALGORITHMS.has(this._algorithm)) {
          return;
        }
        return (ref = this.logger) != null ? typeof ref.warn === "function" ? ref.warn(`[SecurityManager] Algorithm '${this._algorithm}' is not in the supported set — decryption may fail`) : void 0 : void 0;
      }

      _configureLogger(custom) {
        if (isPlainObject(custom) && ['debug', 'info', 'warn', 'error'].every(function(m) {
          return isFunction(custom[m]);
        })) {
          return this.logger = custom;
        } else {
          return this.logger = console;
        }
      }

      inspect() {
        if (this._redactInspect) {
          return '[SecurityManager]';
        } else {
          return `[SecurityManager algorithm=${this._algorithm}]`;
        }
      }

      toJSON() {
        if (this._redactInspect) {
          return {
            type: 'SecurityManager',
            version: SecurityManager.VERSION
          };
        } else {
          return {
            type: 'SecurityManager',
            algorithm: this._algorithm,
            version: SecurityManager.VERSION
          };
        }
      }

      _ensureNotDestroyed() {
        if (this._destroyed) {
          throw new SecurityError('SecurityManager instance has been destroyed');
        }
      }

      // ── HMAC key derivation ────────────────────────────────────────────────────
      _hmacKey() {
        if (this._hmacKeyBuf != null) {
          return this._hmacKeyBuf;
        }
        if (this._legacyHmacKey) {
          this._hmacKeyBuf = crypto.createHash('sha256').update(HMAC_KEY_LABEL).update(this.keyBuffer).digest();
        } else {
          this._hmacKeyBuf = crypto.createHmac('sha256', this.keyBuffer).update(HMAC_KEY_LABEL).digest();
        }
        return this._hmacKeyBuf;
      }

      generateKey() {
        return crypto.randomBytes(this._aesKeyLength).toString('hex');
      }

      _pepperInput(data, pepper) {
        if (pepper != null) {
          return `${data}:${pepper}`;
        } else {
          return data;
        }
      }

      // ── Encryption: shared internal helpers ────────────────────────────────────
      _formatEncrypted(iv, body, tagOrMac) {
        if (this._isGCM) {
          return `${iv.toString('base64')}:${tagOrMac.toString('base64')}:${body.toString('base64')}`;
        } else {
          return `${iv.toString('base64')}:${body.toString('base64')}:${tagOrMac.toString('base64')}`;
        }
      }

      _parseEncrypted(text) {
        var a, b, c, iv, parts;
        parts = text.split(':');
        if (parts.length !== 3) {
          return null;
        }
        [a, b, c] = parts;
        if (!(a && b && c && BASE64_RE.test(a) && BASE64_RE.test(b) && BASE64_RE.test(c))) {
          return null;
        }
        iv = Buffer.from(a, 'base64');
        if (this._isGCM) {
          return {
            iv,
            tag: Buffer.from(b, 'base64'),
            body: Buffer.from(c, 'base64')
          };
        } else {
          return {
            iv,
            body: Buffer.from(b, 'base64'),
            mac: Buffer.from(c, 'base64')
          };
        }
      }

      _encryptInternal(raw) {
        var cipher, enc, iv, mac, tag;
        iv = crypto.randomBytes(this._ivLength);
        cipher = crypto.createCipheriv(this._algorithm, this.keyBuffer, iv);
        enc = Buffer.concat([cipher.update(raw, 'utf8'), cipher.final()]);
        if (this._isGCM) {
          tag = cipher.getAuthTag();
          return this._formatEncrypted(iv, enc, tag);
        } else {
          mac = crypto.createHmac('sha256', this._hmacKey()).update(iv).update(enc).digest();
          return this._formatEncrypted(iv, enc, mac);
        }
      }

      _decryptInternal(parsed) {
        var body, decipher, expected, iv, mac, tag;
        ({iv, body} = parsed);
        if (this._isGCM) {
          ({tag} = parsed);
          decipher = crypto.createDecipheriv(this._algorithm, this.keyBuffer, iv);
          decipher.setAuthTag(tag);
          return Buffer.concat([decipher.update(body), decipher.final()]);
        } else {
          ({mac} = parsed);
          expected = crypto.createHmac('sha256', this._hmacKey()).update(iv).update(body).digest();
          if (!constantTimeCompare(expected, mac)) {
            throw new DecryptionError('HMAC verification failed — data may be tampered');
          }
          decipher = crypto.createDecipheriv(this._algorithm, this.keyBuffer, iv);
          return Buffer.concat([decipher.update(body), decipher.final()]);
        }
      }

      // ── Encryption: public API ─────────────────────────────────────────────────
      encrypt(plaintext) {
        var err, raw;
        this._ensureNotDestroyed();
        try {
          if (plaintext == null) {
            throw new EncryptionError('Cannot encrypt null or undefined');
          }
          raw = isString(plaintext) ? plaintext : JSON.stringify(plaintext);
          if (!isNonEmptyString(raw)) {
            throw new EncryptionError('Empty payload — nothing to encrypt');
          }
          return this._encryptInternal(raw);
        } catch (error) {
          err = error;
          if (err instanceof SecurityError) {
            throw err;
          }
          this.logger.error('[SecurityManager.encrypt] failed:', err != null ? err.message : void 0);
          throw new EncryptionError((err != null ? err.message : void 0) || 'Unknown encryption error', err);
        }
      }

      decrypt(encryptedText) {
        var err, parsed, plain, plainStr;
        this._ensureNotDestroyed();
        if (!isNonEmptyString(encryptedText)) {
          this.logger.debug('[SecurityManager.decrypt] rejected: non-string or empty input');
          return null;
        }
        try {
          parsed = this._parseEncrypted(encryptedText);
          if (parsed == null) {
            this.logger.warn('[SecurityManager.decrypt] rejected: malformed payload');
            return null;
          }
          plain = this._decryptInternal(parsed);
          plainStr = plain.toString('utf8');
          try {
            return JSON.parse(plainStr);
          } catch (error) {
            return plainStr;
          }
        } catch (error) {
          err = error;
          this.logger.warn('[SecurityManager.decrypt] failed:', (err != null ? err.message : void 0) || 'unknown');
          return null;
        }
      }

      decryptOrThrow(encryptedText) {
        var err, parsed, plain, plainStr;
        if (!isNonEmptyString(encryptedText)) {
          throw new DecryptionError('Non-string or empty input');
        }
        try {
          parsed = this._parseEncrypted(encryptedText);
          if (parsed == null) {
            throw new DecryptionError('Malformed payload — expected 3 colon-separated base64 segments');
          }
          plain = this._decryptInternal(parsed);
        } catch (error) {
          err = error;
          if (err instanceof SecurityError) {
            throw err;
          }
          throw new DecryptionError((err != null ? err.message : void 0) || 'Unknown decryption error', err);
        }
        plainStr = plain.toString('utf8');
        try {
          return JSON.parse(plainStr);
        } catch (error) {
          return plainStr;
        }
      }

      isEncryptedFormat(text) {
        var parts;
        if (!isNonEmptyString(text)) {
          return false;
        }
        parts = text.split(':');
        return parts.length === 3 && parts.every(function(p) {
          return isNonEmptyString(p) && BASE64_RE.test(p);
        });
      }

      peekEncrypted(text) {
        var iv;
        if (!this.isEncryptedFormat(text)) {
          return null;
        }
        ({iv} = this._parseEncrypted(text));
        return {
          ivLength: iv.length,
          hasTag: this._isGCM,
          hasMac: !this._isGCM
        };
      }

      getEncryptionInfo() {
        return {
          algorithm: this._algorithm,
          aesKeyLength: this._aesKeyLength,
          ivLength: this._ivLength,
          isGCM: this._isGCM,
          legacyHmacKey: this._legacyHmacKey,
          version: SecurityManager.VERSION
        };
      }

      rotateKey(newKey) {
        var err, old;
        this._ensureNotDestroyed();
        old = this.keyBuffer;
        try {
          this.keyBuffer = coerceKey(newKey, this._aesKeyLength, this.logger);
        } catch (error) {
          err = error;
          this.keyBuffer = old; // rollback
          throw err;
        }
        this._hmacKeyBuf = null;
        this.logger.info('[SecurityManager] Encryption key rotated');
        zeroBuffer(old);
      }

      destroy() {
        if (this._destroyed) {
          return;
        }
        this._destroyed = true;
        zeroBuffer(this.keyBuffer);
        this.keyBuffer = null;
        zeroBuffer(this._hmacKeyBuf);
        this._hmacKeyBuf = null;
        this._rateLimitBuckets.clear();
        this.logger.info('[SecurityManager] Instance destroyed — key material zeroed');
      }

      // ── Hashing ────────────────────────────────────────────────────────────────
      hash(data, salt = null, pepper = null) {
        return this._hash(data, salt, pepper, false);
      }

      hashSync(data, salt = null, pepper = null) {
        return this._hash(data, salt, pepper, true);
      }

      async _scryptDerive(fnName, input, saltBuf, sync) {
        if (sync) {
          return crypto.scryptSync(input, saltBuf, this._scryptKeyLength, this._scryptOptions);
        } else {
          return (await scryptAsync(input, saltBuf, this._scryptKeyLength, this._scryptOptions));
        }
      }

      _hash(data, salt, pepper, sync) {
        var derived, err, fnName, input, saltBuf;
        fnName = sync ? 'hashSync' : 'hash';
        try {
          if (!isString(data)) {
            throw new HashingError(`${fnName}() input must be a string`);
          }
          saltBuf = parseSalt(salt, this._saltLength);
          input = this._pepperInput(data, pepper);
          derived = this._scryptDerive(fnName, input, saltBuf, sync);
          if (!(isBuffer(derived) && derived.length === this._scryptKeyLength)) {
            throw new HashingError('scrypt produced unexpected output');
          }
          return `${saltBuf.toString('hex')}:${derived.toString('hex')}`;
        } catch (error) {
          err = error;
          if (err instanceof SecurityError) {
            throw err;
          }
          this.logger.error(`[SecurityManager.${fnName}] failed:`, err != null ? err.message : void 0);
          throw new HashingError((err != null ? err.message : void 0) || 'Hashing failed', err);
        }
      }

      verifyHash(data, hashedData, pepper = null) {
        return this._verifyHash(data, hashedData, pepper, false);
      }

      verifyHashSync(data, hashedData, pepper = null) {
        return this._verifyHash(data, hashedData, pepper, true);
      }

      _verifyHash(data, hashedData, pepper, sync) {
        var derived, err, expected, expectedHex, fnName, input, saltBuf, saltHex;
        fnName = sync ? 'verifyHashSync' : 'verifyHash';
        try {
          if (!isString(data)) {
            return false;
          }
          if (!(isString(hashedData) && hashedData.includes(':'))) {
            return false;
          }
          [saltHex, expectedHex] = hashedData.split(':');
          if (!((saltHex != null) && (expectedHex != null))) {
            return false;
          }
          saltBuf = Buffer.from(saltHex, 'hex');
          expected = Buffer.from(expectedHex, 'hex');
          input = this._pepperInput(data, pepper);
          derived = this._scryptDerive(fnName, input, saltBuf, sync);
          if (derived.length !== expected.length) {
            return false;
          }
          return constantTimeCompare(derived, expected);
        } catch (error) {
          err = error;
          this.logger.warn(`[SecurityManager.${fnName}] failed:`, err != null ? err.message : void 0);
          return false;
        }
      }

      // ── Tokens ─────────────────────────────────────────────────────────────────
      generateToken(lengthBytes = 32) {
        var n;
        n = isPositiveInt(lengthBytes) ? lengthBytes : 32;
        return crypto.randomBytes(n).toString('hex');
      }

      generateCSRFToken() {
        return crypto.randomBytes(16).toString('base64url');
      }

      verifyCSRFToken(expected, actual) {
        if (!(isNonEmptyString(expected) && isNonEmptyString(actual))) {
          throw new CSRFTokenError('Both expected and actual tokens must be non-empty strings');
        }
        return SecurityManager.secureCompare(expected, actual);
      }

      // ── JWT ────────────────────────────────────────────────────────────────────
      signSecureJWT(payload, jwtSecret, options = {}) {
        var err, jwt, opts;
        jwt = _jwtLoader();
        if (jwt == null) {
          throw new SecurityError('jsonwebtoken package not available');
        }
        if (!isPlainObject(payload)) {
          throw new SecurityError('signSecureJWT: payload must be an object');
        }
        if (!isNonEmptyString(jwtSecret)) {
          throw new SecurityError('signSecureJWT: jwtSecret must be a non-empty string');
        }
        opts = {
          algorithm: 'HS256',
          ...options
        };
        try {
          return jwt.sign(payload, jwtSecret, opts);
        } catch (error) {
          err = error;
          this.logger.error('[SecurityManager.signSecureJWT] failed:', err != null ? err.message : void 0);
          throw new SecurityError(`JWT signing failed: ${err != null ? err.message : void 0}`, err);
        }
      }

      verifySecureJWT(token, jwtSecret, options = {}) {
        var code, decoded, err, jwt, msg, opts;
        jwt = _jwtLoader();
        if (jwt == null) {
          return {
            valid: false,
            data: null,
            error: 'jsonwebtoken package not available'
          };
        }
        try {
          if (!isNonEmptyString(token)) {
            throw new SecurityError('Token must be a non-empty string');
          }
          if (!isNonEmptyString(jwtSecret)) {
            throw new SecurityError('jwtSecret must be a non-empty string');
          }
          opts = {
            algorithms: ['HS256'],
            ...options
          };
          decoded = jwt.verify(token, jwtSecret, opts);
          return {
            valid: true,
            data: decoded
          };
        } catch (error) {
          err = error;
          code = (err != null ? err.name : void 0) === 'TokenExpiredError' ? 'token_expired' : (err != null ? err.name : void 0) === 'NotBeforeError' ? 'token_not_active' : (err != null ? err.name : void 0) === 'JsonWebTokenError' ? 'token_invalid' : 'verify_failed';
          msg = err instanceof SecurityError ? err.message : (err != null ? err.message : void 0) || 'Unknown error';
          this.logger.warn('[SecurityManager.verifySecureJWT] failed:', msg);
          return {
            valid: false,
            data: null,
            error: msg,
            code
          };
        }
      }

      // ── HMAC ───────────────────────────────────────────────────────────────────
      hmac(data, key = null) {
        var d, k;
        if (data == null) {
          throw new SecurityError('hmac() data must not be null or undefined');
        }
        k = key != null ? (isBuffer(key) ? key : Buffer.from(String(key))) : this.keyBuffer;
        d = isBuffer(data) ? data : Buffer.from(String(data), 'utf8');
        return crypto.createHmac('sha256', k).update(d).digest('hex');
      }

      verifyHmac(data, expectedHex, key = null) {
        var computed, expected;
        try {
          if (!isNonEmptyString(expectedHex)) {
            return false;
          }
          computed = Buffer.from(this.hmac(data, key), 'hex');
          expected = Buffer.from(expectedHex, 'hex');
          return constantTimeCompare(computed, expected);
        } catch (error) {
          return false;
        }
      }

      // ── Secure storage (sync or async store) ───────────────────────────────────
      secureStore(store, key, data) {
        var enc, err, res;
        try {
          if (!isFunction(store != null ? store.set : void 0)) {
            throw new SecurityError('secureStore: store.set is required');
          }
          if (!isNonEmptyString(key)) {
            throw new SecurityError('secureStore: key must be a non-empty string');
          }
          enc = this.encrypt(data);
          res = store.set(key, enc);
          if (res && typeof (res != null ? res.then : void 0) === 'function') {
            return res.then(function() {
              return true;
            }).catch((err) => {
              this.logger.error('[SecurityManager.secureStore] async failed:', err != null ? err.message : void 0);
              return false;
            });
          } else {
            return true;
          }
        } catch (error) {
          err = error;
          this.logger.error('[SecurityManager.secureStore] failed:', err != null ? err.message : void 0);
          return false;
        }
      }

      secureRetrieve(store, key) {
        var encrypted, err, handle;
        try {
          if (!isFunction(store != null ? store.get : void 0)) {
            throw new SecurityError('secureRetrieve: store.get is required');
          }
          if (!isNonEmptyString(key)) {
            throw new SecurityError('secureRetrieve: key must be a non-empty string');
          }
          encrypted = store.get(key);
          handle = function(enc) {
            if (enc == null) {
              return null;
            }
            return this.decrypt(enc);
          };
          if (encrypted && typeof (encrypted != null ? encrypted.then : void 0) === 'function') {
            return encrypted.then(handle.bind(this)).catch((err) => {
              this.logger.warn('[SecurityManager.secureRetrieve] async failed:', err != null ? err.message : void 0);
              return null;
            });
          } else {
            return handle.call(this, encrypted);
          }
        } catch (error) {
          err = error;
          this.logger.warn('[SecurityManager.secureRetrieve] failed:', err != null ? err.message : void 0);
          return null;
        }
      }

      // ── Sanitization ───────────────────────────────────────────────────────────
      sanitizeForStorage(obj, maxDepth = 20) {
        var depth, seen, walk;
        depth = isPositiveInt(maxDepth) ? maxDepth : 20;
        seen = new WeakSet();
        walk = function(value, d) {
          var item, key, result, type, val;
          if (value == null) {
            return value;
          }
          if (d > depth) {
            return '[Sanitized: max depth]';
          }
          type = typeof value;
          if (type === 'string' || type === 'number' || type === 'boolean' || type === 'bigint' || type === 'symbol') {
            return value;
          }
          if (seen.has(value)) {
            return '[Circular]';
          }
          seen.add(value);
          if (isBuffer(value)) {
            return '[Buffer]';
          }
          if (value instanceof Date) {
            return value.toISOString();
          }
          if (value instanceof Error) {
            return `[Error: ${value.message}]`;
          }
          if (Array.isArray(value)) {
            return (function() {
              var i, len, results;
              results = [];
              for (i = 0, len = value.length; i < len; i++) {
                item = value[i];
                results.push(walk(item, d + 1));
              }
              return results;
            })();
          }
          if (value instanceof Map) {
            result = {};
            value.forEach(function(v, k) {
              return result[String(k)] = walk(v, d + 1);
            });
            return result;
          }
          if (value instanceof Set) {
            return (function() {
              var i, len, results;
              results = [];
              for (i = 0, len = value.length; i < len; i++) {
                item = value[i];
                results.push(walk(item, d + 1));
              }
              return results;
            })();
          }
          result = {};
          for (key in value) {
            if (!hasProp.call(value, key)) continue;
            val = value[key];
            result[key] = isString(key) && SENSITIVE_RE.test(key) ? '[Redacted]' : walk(val, d + 1);
          }
          return result;
        };
        return walk(obj, 0);
      }

      maskSensitive(text, keepChars = 4, maskChar = '*') {
        var char, head, keep, mid, tail;
        if (!isNonEmptyString(text)) {
          return '';
        }
        keep = isPositiveInt(keepChars) ? keepChars : 4;
        char = isNonEmptyString(maskChar) ? maskChar[0] : '*';
        // Clamp keep so head+tail never exceeds length
        keep = Math.min(keep, Math.floor(text.length / 2));
        if (text.length <= keep * 2) {
          return char.repeat(text.length);
        }
        head = text.slice(0, keep);
        tail = text.slice(-keep);
        mid = char.repeat(Math.max(1, text.length - keep * 2));
        return `${head}${mid}${tail}`;
      }

      // ── Rate limiting ──────────────────────────────────────────────────────────
      validateRateLimit(key, windowMs, maxCalls) {
        var allowed, arr, cutoff, i, len, now, ref, remaining, retryAfterMs, ts, writeIdx;
        if (!isNonEmptyString(key)) {
          throw new RateLimitError('invalid-key', 0);
        }
        if (!isPositiveInt(windowMs)) {
          throw new RateLimitError(key, 0);
        }
        if (!isPositiveInt(maxCalls)) {
          throw new RateLimitError(key, 0);
        }
        now = Date.now();
        cutoff = now - windowMs;
        arr = (ref = this._rateLimitBuckets.get(key)) != null ? ref : [];
        // In-place prune: drop timestamps older than the cutoff
        writeIdx = 0;
        for (i = 0, len = arr.length; i < len; i++) {
          ts = arr[i];
          if (ts > cutoff) {
            arr[writeIdx++] = ts;
          }
        }
        arr.length = writeIdx;
        allowed = arr.length < maxCalls;
        if (allowed) {
          arr.push(now);
        }
        this._rateLimitBuckets.set(key, arr);
        remaining = Math.max(0, maxCalls - arr.length);
        retryAfterMs = allowed ? 0 : arr.length > 0 ? Math.max(0, arr[0] + windowMs - now) : 0;
        return {allowed, remaining, retryAfterMs};
      }

      clearRateLimit(key) {
        this._rateLimitBuckets.delete(key);
      }

      pruneRateLimits(maxAgeMs = 60000) {
        var cutoff, now, removed;
        now = Date.now();
        cutoff = now - (isPositiveInt(maxAgeMs) ? maxAgeMs : 60000);
        removed = 0;
        this._rateLimitBuckets.forEach((arr, key) => {
          var i, len, ts, writeIdx;
          writeIdx = 0;
          for (i = 0, len = arr.length; i < len; i++) {
            ts = arr[i];
            if (ts > cutoff) {
              arr[writeIdx++] = ts;
            }
          }
          if (writeIdx === 0) {
            this._rateLimitBuckets.delete(key);
            return removed++;
          } else {
            return arr.length = writeIdx;
          }
        });
        return removed;
      }

      resetRateLimits() {
        var count;
        count = this._rateLimitBuckets.size;
        this._rateLimitBuckets.clear();
        return count;
      }

    };

    SecurityManager.SecurityError = SecurityError;

    SecurityManager.EncryptionError = EncryptionError;

    SecurityManager.DecryptionError = DecryptionError;

    SecurityManager.HashingError = HashingError;

    SecurityManager.KeyLengthError = KeyLengthError;

    SecurityManager.CSRFTokenError = CSRFTokenError;

    SecurityManager.RateLimitError = RateLimitError;

    SecurityManager.VERSION = '2.2.0';

    // ── Read-only accessors ────────────────────────────────────────────────────
    Object.defineProperties(SecurityManager.prototype, {
      algorithm: {
        enumerable: true,
        get: function() {
          return this._algorithm;
        }
      },
      aesKeyLength: {
        enumerable: true,
        get: function() {
          return this._aesKeyLength;
        }
      },
      ivLength: {
        enumerable: true,
        get: function() {
          return this._ivLength;
        }
      },
      saltLength: {
        enumerable: true,
        get: function() {
          return this._saltLength;
        }
      },
      scryptKeyLength: {
        enumerable: true,
        get: function() {
          return this._scryptKeyLength;
        }
      },
      scryptOptions: {
        enumerable: true,
        get: function() {
          return Object.freeze({...this._scryptOptions});
        }
      },
      legacyHmacKey: {
        enumerable: true,
        get: function() {
          return this._legacyHmacKey;
        }
      },
      isDestroyed: {
        enumerable: true,
        get: function() {
          return this._destroyed;
        }
      }
    });

    // Optional `using` semantics (TC39 explicit-resource-management)
    if (Symbol.dispose != null) {
      SecurityManager.prototype[Symbol.dispose] = function() {
        return this.destroy();
      };
    }

    if (Symbol.asyncDispose != null) {
      SecurityManager.prototype[Symbol.asyncDispose] = function() {
        this.destroy();
        return Promise.resolve();
      };
    }

    return SecurityManager;

  }).call(this);

  // ── Export ───────────────────────────────────────────────────────────────────
  module.exports = SecurityManager;

}).call(this);
